tasks:
  - command: |
      export APP_URL=`gp url 8080 | sed 's~https://~~'`
      docker image pull dockware/dev:latest
      docker run -d -p 8080:80 --name shopware dockware/dev
      
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
